CREATE DATABASE HOGARSOL_WEB_DB;

CREATE TABLE ROLES(
	ROLE_ID INT NOT NULL PRIMARY KEY,
    ROLE_NAME VARCHAR(50) NOT NULL,
    ROLE_PERMISSION_TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL,
    USERPASS VARCHAR(255) NOT NULL, 
    USERLASTNAME1 VARCHAR(100) NOT NULL,
    USERLASTNAME2 VARCHAR(100) NOT NULL,
    USERMAIL VARCHAR(255) NOT NULL,
    CONFIRMATION_CODE VARCHAR(50) NOT NULL,
    USER_CONFIRMATION BOOLEAN DEFAULT FALSE,
    USER_ACTIVE BOOLEAN DEFAULT TRUE, 
    ROLE_ID INT DEFAULT 2, 
    FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ROLE_ID),
    CONSTRAINT UNIQUE (USERMAIL),
    CONSTRAINT UNIQUE (CONFIRMATION_CODE)
);

CREATE TABLE NEWSLETTER (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERMAIL VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    USERLASTNAME1 VARCHAR(100) NOT NULL,
    USERLASTNAME2 VARCHAR(100),
    USER_ACTIVE BOOLEAN NOT NULL
);

INSERT INTO ROLES (ROLE_ID, ROLE_NAME, ROLE_PERMISSION_TYPE)
VALUES
(1, 'Admin', 'Admin'),
(2, 'User', 'User');